### Listar todos os pets
GET http://localhost:8080/pets

### Cadastrar um novo pet
POST http://localhost:8080/pets
Content-Type: application/json

{
  "name": "Thor",
  "age": 2,
  "imageUrl": "https://plcedog.net/500/500"
}

### Buscar um pet específico
GET http://localhost:8080/pets/1